# Model arguments
model_name_or_path: Qwen/Qwen3-8B
run_name: "rlcr_multi_standard"
output_dir: data/brier_weight_analysis/rlcr_multi_standard
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: mehuldamani/medDataset_25k

# GRPO trainer config
format_pattern: "multi_answer"
gradient_accumulation_steps: 32
hub_strategy: "end"
learning_rate: 1e-06
max_prompt_length: 3072
max_completion_length: 1536
max_steps: -1
num_generations: 32
num_train_epochs: 1
per_device_eval_batch_size: 32
per_device_train_batch_size: 6
num_candidates: 3
push_to_hub: true
enable_adaptive_brier: false
reward_funcs: ["format","accuracy","brier"]
reward_weights: [0.5,0.5,0.5]
seed: 43
sys_prompt_name: "og_multi_answer_short_medical"
temperature: 0.7 
vllm_gpu_memory_utilization: 0.4
vllm_importance_sampling_correction: false
warmup_ratio: 0.05

# accuracy_via_judge: true  # Set to true to use Qwen3 8B as judge for accuracy evaluation
# judge_gpu_id: 0  # GPU ID to run the judge model on (if None, uses default GPU)



# Logging and checkpointing
eval_strategy: "steps" 
eval_steps: 50
eval_on_start: false
log_completions: true
log_level: info
logging_steps: 1
logging_strategy: steps
overwrite_output_dir: true
save_strategy: "steps"
save_steps: 60
save_total_limit: 1
report_to:
- wandb
use_vllm: true

